---
- hosts: all
  become: yes
  tasks:
    - name: SSH key
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"

    - name: apt full-upgrade
      apt:
        upgrade: full
        update_cache: true
        autoclean: true
        autoremove: true

    - name: Install Ubuntu HWE
      apt:
        name: linux-generic-hwe-22.04
        update_cache: true
        autoclean: true
        autoremove: true

    - name: Deps for Parallels
      apt:
        name:
          - libelf-dev
          - dkms
          - binfmt-support
        update_cache: true
